version: "3"

# declaração dos serviços
services:
  # nome do serviço
  frontend:
    # nome do container
    container_name: Module2-StartingCode
    # diretório onde o Dockerfile está localizado para fazer o build e gerar a imagem da aplicação
    build:
      context: ./Module2-StartingCode
      dockerfile: Dockerfile
    # volumes compartilhados entre máquina e container
    volumes:
      - ./Module2-StartingCode:/src
      - dependencias_02:/src/node_modules
    # mapeamento de portas 3000 -> 3000 (máquina -> container)
    ports:
      - "4200:4200"
    # comando a ser utilizado quando o container for criado
    command: ng serve --host 0.0.0.0

# volumes docker a serem criados
volumes:
  # nove do volume docker criado (pode ser removido com a flag -v)
  dependencias_02:
